[package]
name = "castor-provider"
version.workspace = true
edition.workspace = true

[features]
cuda = ["castor/cuda"]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
castor = { workspace = true }
